version: '3.9'
services:

  grafana:
    image: grafana/grafana:9.1.3
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana

  influxdb2:
    image: influxdb:2.6
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=$DOCKER_INFLUXDB_INIT_MODE 
      - DOCKER_INFLUXDB_INIT_USERNAME=$DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

  telegraf:
    image: telegraf:1.25
    #user: telegraf:<your docker id> to get you docker id on Linux: $(getent group docker | cut -d: -f3)
    user: telegraf:965
    ports:
      - 8092:8092
      - 8094:8094
      - 8125:8125
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$DOCKER_INFLUXDB_INIT_BUCKET
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    depends_on:
      - influxdb2
      
volumes:
  grafana-data: